FROM nixos/nix:2.2.1

RUN \
  nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs && \
  nix-channel --update && \
  nix-env -iA nixpkgs.openssh \
              nixpkgs.rsync \
              nixpkgs.stack \
              nixpkgs.texlive.combined.scheme-full

ENV \
  LANG=en_GB.UTF-8 \
  LC_ALL=en_GB.UTF-8 \
  LC_CTYPE=en_GB.UTF-8
