FROM ci-registry:5000/ci-base:latest

RUN nix-env -iA \
        nixpkgs.haskellPackages.pandoc \
        nixpkgs.haskellPackages.pandoc-sidenote \
        nixpkgs.stack \
        nixpkgs.texlive.combined.scheme-full
