resources:
- name: concoursefiles-git
  type: git
  source:
    branch: master
    uri: https://github.com/barrucadu/concoursefiles.git

- name: ci-agent-image
  type: docker-image
  source:
    repository: ci-registry:5000/ci-agent
    insecure_registries: ["ci-registry:5000"]

jobs:
- name: ci-agent
  serial: true
  plan:
    - get: concoursefiles-git

    - task: tag
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
        outputs:
          - name: tag
        run:
          path: sh
          args:
            - -cex
            - |
              date +'%s' > tag/timestamp

    - put: ci-agent-image
      params:
        build: concoursefiles-git/
        dockerfile: concoursefiles-git/Dockerfile.ci-agent
        tag_file: tag/timestamp
        tag_as_latest: true
