# common params for building a docker image
x-params-put: &x-params-put
  build: concoursefiles-git/
  tag_as_latest: true

resources:
- name: concoursefiles-git
  type: git
  source:
    uri: https://github.com/barrucadu/concoursefiles.git

- name: ci-base-image
  type: docker-image
  source:
    repository: ci-registry:5000/ci-base
    insecure_registries: ["ci-registry:5000"]

- name: ci-agent-image
  type: docker-image
  source:
    repository: ci-registry:5000/ci-agent
    insecure_registries: ["ci-registry:5000"]

- name: ci-resource-rsync-image
  type: docker-image
  source:
    repository: ci-registry:5000/ci-resource-rsync
    insecure_registries: ["ci-registry:5000"]

jobs:
- name: ci-base
  serial: true
  plan:
    - get: concoursefiles-git
    - put: ci-base-image
      params:
        <<: *x-params-put
        dockerfile: concoursefiles-git/Dockerfile.ci-base
- name: ci-agent
  serial: true
  plan:
    - aggregate:
        - get: concoursefiles-git
        - get: ci-base-image
          trigger: true
    - put: ci-agent-image
      params:
        <<: *x-params-put
        dockerfile: concoursefiles-git/Dockerfile.ci-agent
- name: ci-resource-rsync
  serial: true
  plan:
    - aggregate:
        - get: concoursefiles-git
        - get: ci-base-image
          trigger: true
    - put: ci-resource-rsync-image
      params:
        <<: *x-params-put
        dockerfile: concoursefiles-git/Dockerfile.ci-resource-rsync
