resources:
- name: memo-git
  type: git
  source:
    branch: master
    uri: https://github.com/barrucadu/memo.barrucadu.co.uk.git

default_task_config: &DEFAULT_TASK_CONFIG
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: ci-registry:5000/ci-agent
      insecure_registries: ["ci-registry:5000"]

jobs:
- name: memo.barrucadu.co.uk
  serial: true
  plan:
    - get: memo-git
      trigger: true

    - task: build
      config:
        <<: *DEFAULT_TASK_CONFIG
        inputs:
          - name: memo-git
        outputs:
          - name: site
            path: memo-git/_site
        caches:
          - path: .stack
          - path: memo-git/.stack-work
        run:
          path: sh
          args:
            - -cex
            - |
              cd memo-git

              stack --no-terminal build
              stack --no-terminal exec hakyll build

    - task: deploy
      params:
        SSH_PRIVATE_KEY: {{ssh-private-key}}
      config:
        <<: *DEFAULT_TASK_CONFIG
        inputs:
          - name: site
        run:
          path: sh
          args:
            - -ce
            - |
              echo "${SSH_PRIVATE_KEY}" > sshkey
              chmod 700 sshkey

              set -x

              rsync -e 'ssh -o StrictHostKeyChecking=no -i sshkey' -avzc --delete site/ concourseci@barrucadu.co.uk:/srv/http/barrucadu.co.uk/memo/

    - task: notify
      params:
        PLEROMA_PASSWORD: {{pleroma-user-memo-password}}
      config:
        <<: *DEFAULT_TASK_CONFIG
        inputs:
          - name: memo-git
        run:
          path: memo-git/post-pleroma-status
