x-task-config: &x-task-config
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: ci-registry:5000/ci-agent
      insecure_registries: ["ci-registry:5000"]

resource_types:
- name: rsync-resource
  type: docker-image
  source:
      repository: ci-registry:5000/ci-resource-rsync
      insecure_registries: ["ci-registry:5000"]

resources:
- name: docs-git
  type: git
  source:
    uri: https://github.com/uzbl/uzbl.git

- name: website-git
  type: git
  source:
    uri: https://github.com/uzbl/uzbl-website.git

- name: docs-rsync
  type: rsync-resource
  source:
    remote_dir: /srv/http/uzbl.org/uzbl
    private_key: {{ssh-private-key}}

- name: website-rsync
  type: rsync-resource
  source:
    remote_dir: /srv/http/uzbl.org/www
    private_key: {{ssh-private-key}}

jobs:
- name: website
  serial: true
  plan:
    - get: website-git
      trigger: true
    - put: website-rsync
      params:
        path: website-git
        rsync_args: ["--delete", "--exclude=.git/"]
- name: docs
  serial: true
  plan:
    - get: docs-git
      trigger: true
    - put: docs-rsync
      params:
        path: docs-git
        rsync_args: ["--delete", "--exclude=.git/"]
